import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dev-story",
  description: "Generated by shakib",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <nav  className=" flex justify-between px-4 py-3 border-2 border-amber-400">
            <h2 className="text-ig font-semibold" >🐳Dev story</h2>  
            <Header></Header>
        </nav>
        

        {children}

        

        </body>
    </html>
  );
}


